#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bdl (Batch Downloader)
# Started On        - Sat 16 Sep 22:34:12 BST 2017
# Last Change       - Tue 28 Nov 13:06:53 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/wget /sbin/shutdown /bin/{mv,systemctl,sleep,sync,mkdir}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -gt 0 ] && exit 1

DL_DIR="./"
MAIN_DIR="$HOME/.bdl"
LIST_EDITOR_FILE="$MAIN_DIR/editor.conf"
BDL_FILE="$MAIN_DIR/bdl_list.txt"

SHUTDOWN="false"
VERBOSE="false"
NOTIFY="false"
DEBUG="false"

[ $UID -eq 0 ] && XERR "$LINENO" "Root access is not required."
[ "$OSTYPE" == "linux-gnu" ] || XERR "$LINENO" "Unsupported platform."

/bin/mkdir -p "$MAIN_DIR"
[ -f "$BDL_FILE" ] || > "$BDL_FILE"

USAGE(){
	while read -r; do
		echo "$REPLY"
	done <<-EOF
		            BDL - BATCH DOWNLOADER (28th November 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Easily and quickly download a batch of files using wget.

		SYNTAX:     bdl [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.
		            --insert|-I LINK        - Quickly append a link to the download list.
		            --dest|-d PATH          - Where PATH is the location to download.
		            --editor|-E CMD         - Where CMD is the command for your editor.
		            --verbose|-v            - Display wget's more verbose output.
		            --suspend|-s            - Immediately suspend machine when finished.
		            --shutdown|-S           - Like above, but a shutdown after 1 minute.
		            --notify|-N             - Use notify-send to inform of bdl completion.
		            --edit|-e               - Change URL list with an available text editor.
		            --clear|-C              - Empty the bdl download list entirely.
		
		FILE:       All files are found in '\$HOME/.bdl'.
	EOF
}

[ -f "$LIST_EDITOR_FILE" -a -w "$LIST_EDITOR_FILE" -a -s "$LIST_EDITOR_FILE" ] || {
	XERR "$LINENO" "Please choose an editor. See --help for info."
} && LIST_EDITOR=`< "$LIST_EDITOR_FILE"`

INIT_MAIN(){
	[ "$DEBUG" == "true" ] && set -xue
	[ "$VERBOSE" == "true" ] && VFLAG="-v" || VFLAG="--quiet"

	LIST_COUNT=$(
		declare -i LINE=0
		while read -r; do
			LINE+=1
		done < "$BDL_FILE"
		echo "$LINE"
	)

	for LINK in `< "$BDL_FILE"`; {
		/usr/bin/wget --random-wait --continue --tries=1 $VFLAG --max-redirect=1\
			--show-progress "$LINK" -O "${DL_DIR}/${LINK/*\//}"

		/bin/sync "${DL_DIR}/${LINK/*\//}"
	}

	[ "$NOTIFY" == "true" ] && {
		[ -x /usr/bin/notify-send ] && {
			/usr/bin/notify-send "Downloading with bdl is completed."
		} || ERR "$LINENO" "Unable to find notify-send."
	}

	if [ "$SHUTDOWN" == "true" ]; then
		/sbin/shutdown --no-wall +1
		/usr/bin/notify-send "System shutdown in one minute." -i warning -u critical
	elif [ "$SUSPEND" == "true" ]; then
		/usr/bin/notify-send "System will suspend." -i warning -u critical
		/bin/sleep 3s
		/bin/systemctl suspend
	fi
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUG="true" ;;
		--insert|-I)
			shift

			INSERT="true"
			printf "%s\n" "$1" >> "$BDL_FILE" ;;
		--dest|-d)
			shift

			[ -d "$1" ] || {
				XERR "$LINENO" "Destination directory unavailable."
			} && DL_DIR="$1" ;;
		--editor|-E)
			shift

			echo "$1" > "$LIST_EDITOR_FILE"
			exit 0 ;;
		--edit|-e)
			if [ -x "$LIST_EDITOR" ]; then
				$LIST_EDITOR "$BDL_FILE" 2> /dev/null
				exit 0
			else
				XERR "$LINENO" "Unable to execute: $LIST_EDITOR"
			fi ;;
		--clear|-C)
			/bin/mv "$BDL_FILE"{,.old} &> /dev/null
			echo "File '$BDL_FILE' now empty."
			exit 0 ;;
		--verbose|-v)
			VERBOSE="true" ;;
		--notify|-N)
			NOTIFY="true" ;;
		--suspend|-s)
			SUSPEND="true" ;;
		--shutdown|-S)
			SHUTDOWN="true" ;;
	esac

	shift
done

[ "$INSERT" == "true" ] && exit 0

case "$SHUTDOWN" in
	false)
		INIT_MAIN ;;
	true)
		INIT_MAIN SHUTDOWN ;;
esac
