#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - bdl/completion
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Tue 30 Jan 21:24:27 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for bdl.
#----------------------------------------------------------------------------------

_arg_list(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case "${X[0]}" in
			OPTS:)
				IS_OPTS_LINE="true"
				printf "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD="${X[0]/OPTS:}"
	done <<< "$(/usr/bin/bdl -h)"
}

_option(){
	COMPREPLY=($(compgen -W "$(_arg_list)" -- "$2"))
}

complete -F _option -o default bdl
