#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - installit (bdl)
# Started On        - Thu 14 Sep 14:44:27 BST 2017
# Last Change       - Mon 18 Sep 17:17:19 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
ERR(){ echo "ERROR: $1" 1>&2; }

DEPCOUNT=0
for DEP in /usr/bin/wget /bin/{rm,chmod,chown,cat,mkdir}
{
	if ! type -P "$DEP" &> /dev/null
	then
		ERR "Dependency '$DEP' not met."
		let DEPCOUNT++
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

shopt -s extglob

USAGE()
{
	/bin/cat <<-EOF
		            INSTALLIT (18th September 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Installer for many shell programs from terminalforlife.

		SYNTAX:     install_bdl [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug                 - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --update|-U             - Replace and update existing files.
		            --uninstall|-u          - Uninstall files installed here.

		WARNING:    Uninstalling with this program will permanently delete the files it
		            initially installed, but only if you don't have: /usr/bin/gvfs-trash

		            To check for this command, execute the following:

		              which /usr/bin/gvfs-trash
		
		SITE:       https://github.com/terminalforlife
	EOF
}

for ARG in $@
{
	case "$ARG"
	in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--update|-U)
			FORCE_INSTALL="true" ;;
		--uninstall|-u)
			UNINSTALL="true" ;;
		*)
			XERR "Incorrect argument(s) specified." ;;
	esac
}

# [N]ormal [V]er[b]osity
NVB(){ printf "L%-0.3d: %s\n" "$1" "$2"; }

[ $UID -eq 0 ] || XERR "Root access is required."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

GITHUB_URL="https://raw.githubusercontent.com/terminalforlife"
PROJECT="bdl"

if [ "$UNINSTALL" == "true" ]
then
	NVB "$LINENO" "Uninstalling program."
fi

for FILENAME in\
\
	"/usr/bin/$PROJECT":"755"
{
	if ! [ "$UNINSTALL" == "true" ]
	then
		NVB "$LINENO" "Checking conflict: ${FILENAME%:*}"
		if [ -f "${FILENAME%:*}" ]
		then
			if ! [ "$FORCE_INSTALL" == "true" ]
			then
				ERR "Conflict found: ${FILENAME%:*}"
				continue
			else
				NVB "$LINENO" "Item updated: ${FILENAME%:*}"
			fi
		fi

		NVB "$LINENO" "Downloading here: ${FILENAME%:*}"
		/usr/bin/wget -q "$GITHUB_URL"/$PROJECT/master/$PROJECT\
			-O "${FILENAME%:*}"

		NVB "$LINENO" "Correcting attributes: ${FILENAME%:*}"
		/bin/chown root:root "${FILENAME%:*}"
		/bin/chmod ${FILENAME/*:} "${FILENAME%:*}"
	else
		if type -P /usr/bin/gvfs-trash &> /dev/null
		then
			NVB "$LINENO" "Sending to trash: ${FILENAME%:*}"
			if ! /usr/bin/gvfs-trash "${FILENAME%:*}" &> /dev/null
			then
				ERR "Failed to trash: ${FILENAME%:*}"
			fi
		else
			NVB "$LINENO" "Deleting: ${FILENAME%:*}"
			if /bin/rm "${FILENAME%:*}" &> /dev/null
			then
				ERR "Failed to delete: ${FILENAME%:*}"
			fi
		fi
	fi
}

[ "$DEBUGME" == "true" ] && set +xeu || exit 0
